name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: a523f64c-f66c-461e-94a1-ddfdb27f83e6
          heroku_app_name: gislasoncathy
          heroku_email: gislasoncathy@outlook.com
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_CONFIG_FILE_URL: https://gist.githubusercontent.com/gislasoncathy/ae6375170a55df627122edda1e4416c7/raw/config.env
