name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 49b2f46a-6a2b-4c4a-9b95-bfa4eceb3b4f
          heroku_app_name: gislasoncathy
          heroku_email: margretstamm@outlook.com
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_CONFIG_FILE_URL: https://gist.githubusercontent.com/gislasoncathy/ae6375170a55df627122edda1e4416c7/raw/config.env
